services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    env_file:
      - backend/.env
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - postgres